services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app_backend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    networks:
      - todo-network

  nginx:
    image: nginx:alpine
    container_name: todo_nginx
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - todo-network
    depends_on:
      - app

networks:
  todo-network:
    driver: bridge